
-- Genre Inserts
INSERT INTO Genre (genre_id, name) VALUES (1, 'Drama');
INSERT INTO Genre (genre_id, name) VALUES (2, 'Documentary');
INSERT INTO Genre (genre_id, name) VALUES (3, 'Horror');
INSERT INTO Genre (genre_id, name) VALUES (4, 'Music');
INSERT INTO Genre (genre_id, name) VALUES (5, 'Thriller');
INSERT INTO Genre (genre_id, name) VALUES (6, 'N/A');
INSERT INTO Genre (genre_id, name) VALUES (7, 'Biography');
INSERT INTO Genre (genre_id, name) VALUES (8, 'Fantasy');
INSERT INTO Genre (genre_id, name) VALUES (9, 'Action');
INSERT INTO Genre (genre_id, name) VALUES (10, 'Comedy');
INSERT INTO Genre (genre_id, name) VALUES (11, 'Sci-Fi');
INSERT INTO Genre (genre_id, name) VALUES (12, 'Game-Show');
INSERT INTO Genre (genre_id, name) VALUES (13, 'Reality-TV');
INSERT INTO Genre (genre_id, name) VALUES (14, 'Adventure');
INSERT INTO Genre (genre_id, name) VALUES (15, 'News');
INSERT INTO Genre (genre_id, name) VALUES (16, 'Sport');
INSERT INTO Genre (genre_id, name) VALUES (17, 'Family');
INSERT INTO Genre (genre_id, name) VALUES (18, 'Mystery');
INSERT INTO Genre (genre_id, name) VALUES (19, 'Crime');
INSERT INTO Genre (genre_id, name) VALUES (20, 'Romance');
INSERT INTO Genre (genre_id, name) VALUES (21, 'Animation');
INSERT INTO Genre (genre_id, name) VALUES (22, 'Musical');

-- ContentItem Inserts
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Tango of the Widower and Its Distorting Mirror', 'The story of a man whose wife has committed suicide and appears to him as a ghost, following him everywhere and changing his personality.', 'Movie', '2020-09-23', 1, 'https://m.media-amazon.com/images/M/MV5BZWU2NzQ4NDgtZTdlNC00OGQ4LTk0OGItMTliOTE2YTViZmE3XkEyXkFqcGdeQXVyMTAxMDQ0ODk@._V1_SX300.jpg'); -- item_id = 1
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Socialist Realism', 'A satirical reading of the process of the "Unidad Popular" of President Salvador Allende, prior to the military civic coup of 1973 in Chile. The film is a choral story, where different worlds are chained together.', 'Movie', '2023-09-23', 1, 'https://m.media-amazon.com/images/M/MV5BMjc5ZGY1YzItOGJmOC00N2Q3LTk1NzAtYjkxYzVjMjg1ZDE3XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 2
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Uma História de Comboios', 'N/A', 'Movie', '2022-01-01', 2, 'N/A'); -- item_id = 3
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Grizzly II: Revenge', 'All hell breaks loose when a giant Grizzly, reacting to the slaughter of Grizzlies by poachers, attacks at a massive big-band rock concert in the National Park.', 'Movie', '2021-01-08', 3, 'https://m.media-amazon.com/images/M/MV5BMDI3MjVjZDMtYWFhYy00NWIyLWFiZWQtMzFjYmFjMmVkZmI5XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 4
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Grizzly II: Revenge', 'All hell breaks loose when a giant Grizzly, reacting to the slaughter of Grizzlies by poachers, attacks at a massive big-band rock concert in the National Park.', 'Movie', '2021-01-08', 4, 'https://m.media-amazon.com/images/M/MV5BMDI3MjVjZDMtYWFhYy00NWIyLWFiZWQtMzFjYmFjMmVkZmI5XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 5
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Grizzly II: Revenge', 'All hell breaks loose when a giant Grizzly, reacting to the slaughter of Grizzlies by poachers, attacks at a massive big-band rock concert in the National Park.', 'Movie', '2021-01-08', 5, 'https://m.media-amazon.com/images/M/MV5BMDI3MjVjZDMtYWFhYy00NWIyLWFiZWQtMzFjYmFjMmVkZmI5XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 6
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Loading Ludwig', 'In the 21st century, Mimi wakes up and her computer relays the order: "Go back to start. Let''s load Ludwig!" A sort of chase through her past and future begins.', 'Movie', '2022-10-21', 6, 'https://m.media-amazon.com/images/M/MV5BZjFkYTM0Y2ItNzRjZC00NjkxLTg5ODctNjUyOGYzZGYzYzE2XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 7
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Neues in Wittstock', 'Volker Koepp again visits Wittstock an der Dosse in the German state Mark Brandenburg, apx. 90 kilometers from Berlin. This time he interviews female workers in the local textile industry about their experiences after the re-unifi...', 'Movie', '2021-04-30', 2, 'https://m.media-amazon.com/images/M/MV5BNTk4ODExMjItMWIxOS00ZDMyLTlkYWYtNjc2MDZlMjVkNTY4XkEyXkFqcGdeQXVyMTQ0MzMwNQ@@._V1_SX300.jpg'); -- item_id = 8
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('A Dangerous Practice', 'Through the spirit of Dr. Fritz, a German doctor who died during the First World War, José Arigó became a hope for a cure for millions of people by performing spiritual surgery, helping about 2 million people.', 'Movie', '2022-02-24', 7, 'https://m.media-amazon.com/images/M/MV5BMzQzZGQwYmYtMWEyNy00MjZkLWE5OTAtYmIyNDg1NTRiMDdjXkEyXkFqcGdeQXVyNTEyMjMxNw@@._V1_SX300.jpg'); -- item_id = 9
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('A Dangerous Practice', 'Through the spirit of Dr. Fritz, a German doctor who died during the First World War, José Arigó became a hope for a cure for millions of people by performing spiritual surgery, helping about 2 million people.', 'Movie', '2022-02-24', 1, 'https://m.media-amazon.com/images/M/MV5BMzQzZGQwYmYtMWEyNy00MjZkLWE5OTAtYmIyNDg1NTRiMDdjXkEyXkFqcGdeQXVyNTEyMjMxNw@@._V1_SX300.jpg'); -- item_id = 10
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Nine Ball', 'N/A', 'Movie', '2023-03-25', 6, 'https://m.media-amazon.com/images/M/MV5BNGMyNmQyYTctYTlmNS00NzAzLWI5ZDQtY2UwN2Q0N2U0Mzk5XkEyXkFqcGdeQXVyNDY5NzM3NzY@._V1_SX300.jpg'); -- item_id = 11
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Yo-TV', 'N/A', 'TV Show', '2020-01-01', 6, 'N/A'); -- item_id = 12
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Heartland of Darkness', 'Single father Paul Henson purchases a newspaper in the small town of Copperton, Ohio and moves there with his teenage daughter Christina. The two soon come to realize the townsfolk, led by the evil Reverend Donovan, are actually S...', 'Movie', '2022-11-22', 3, 'https://m.media-amazon.com/images/M/MV5BYzYzNzI2YTctYWNhZC00Y2EzLWFmMTUtNDFiZmY5NTQ1ZGZlXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 13
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Superboy & Supergirl & 7 Monster', 'N/A', 'Movie', '2022-03-12', 6, 'N/A'); -- item_id = 14
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Perfect Shadow', 'N/A', 'Movie', '2024-01-01', 6, 'N/A'); -- item_id = 15
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Black Star: Autobiography of a Close Friend', 'Prequel to Tom Joslin''s 1993 AIDS video diary SILVERLAKE LIFE: The View From Here. Mark and Tom in happier times. A mixed-genre experimental documentary about coming out of the closet in the early years of the gay liberation movem...', 'Movie', '2022-10-28', 2, 'N/A'); -- item_id = 16
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Noticiero 24 horas', 'N/A', 'TV Show', '2020-01-01', 6, 'N/A'); -- item_id = 17
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('In the Land of the Blind', 'N/A', 'Movie', '2024-01-01', 6, 'N/A'); -- item_id = 18
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Mugen ryûkyû tsuru Henrî', 'This road film revolves around an Okinawan folk song singer Tsuru and her son Henry''s filmmaking journey. Taiwanese singers CHIN Man-wang, LEE Ping-huei, and acclaimed actress CHEN Shiang-chyi all make cameo appearances. After dec...', 'Movie', '2021-05-03', 1, 'https://m.media-amazon.com/images/M/MV5BOWZlMmY5NzgtODQ0Yi00NTFmLTgwNzgtY2I5YjU5NjJiZGYzXkEyXkFqcGdeQXVyNDUxNjc5NjY@._V1_SX300.jpg'); -- item_id = 19
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Mugen ryûkyû tsuru Henrî', 'This road film revolves around an Okinawan folk song singer Tsuru and her son Henry''s filmmaking journey. Taiwanese singers CHIN Man-wang, LEE Ping-huei, and acclaimed actress CHEN Shiang-chyi all make cameo appearances. After dec...', 'Movie', '2021-05-03', 8, 'https://m.media-amazon.com/images/M/MV5BOWZlMmY5NzgtODQ0Yi00NTFmLTgwNzgtY2I5YjU5NjJiZGYzXkEyXkFqcGdeQXVyNDUxNjc5NjY@._V1_SX300.jpg'); -- item_id = 20
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Radha Krishna', 'N/A', 'Movie', '2020-01-01', 1, 'N/A'); -- item_id = 21
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Incredible Shrinking Man', 'N/A', 'Movie', '2025-01-01', 9, 'N/A'); -- item_id = 22
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Incredible Shrinking Man', 'N/A', 'Movie', '2025-01-01', 10, 'N/A'); -- item_id = 23
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Incredible Shrinking Man', 'N/A', 'Movie', '2025-01-01', 11, 'N/A'); -- item_id = 24
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('A Praga', 'While out for a walk in the countryside, Marina and Juvenal stop to take some pictures in front of an old woman''s house. Annoyed, the old woman turns out to be a witch and casts a curse on the young couple.', 'Movie', '2021-10-15', 3, 'https://m.media-amazon.com/images/M/MV5BNjA0MmE1MzYtNjE3OC00MTgzLTk5OWEtYzNkZGVjMTc0NzQyXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 25
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Taniec trzcin', 'N/A', 'Movie', '2023-01-01', 2, 'N/A'); -- item_id = 26
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Big Brother', 'The Portuguese version of the hit reality TV show. A group of people from a variety of backgrounds are locked in the same house, where they must try to get along well enough to keep from killing each other. The house has been wire...', 'TV Show', '2020-01-01', 12, 'https://m.media-amazon.com/images/M/MV5BZTI3ZGEyYjgtOGRkYS00YzQ3LTg0ZDktYWE2NmJlZTJhOTUxXkEyXkFqcGdeQXVyNDg5MjMyMTM@._V1_SX300.jpg'); -- item_id = 27
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Big Brother', 'The Portuguese version of the hit reality TV show. A group of people from a variety of backgrounds are locked in the same house, where they must try to get along well enough to keep from killing each other. The house has been wire...', 'TV Show', '2020-01-01', 13, 'https://m.media-amazon.com/images/M/MV5BZTI3ZGEyYjgtOGRkYS00YzQ3LTg0ZDktYWE2NmJlZTJhOTUxXkEyXkFqcGdeQXVyNDg5MjMyMTM@._V1_SX300.jpg'); -- item_id = 28
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Gernstl unterwegs', 'N/A', 'TV Show', '2022-01-01', 6, 'N/A'); -- item_id = 29
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Universal Groove', 'A quick trip through the underground party scene as seen through the memories of eight people coming back to reality.', 'Movie', '2007-12-01', 1, 'https://m.media-amazon.com/images/M/MV5BMjE1NTQ5OTk3NF5BMl5BanBnXkFtZTcwMjQxNjE0MQ@@._V1_SX300.jpg'); -- item_id = 30
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Universal Groove', 'A quick trip through the underground party scene as seen through the memories of eight people coming back to reality.', 'Movie', '2007-12-01', 8, 'https://m.media-amazon.com/images/M/MV5BMjE1NTQ5OTk3NF5BMl5BanBnXkFtZTcwMjQxNjE0MQ@@._V1_SX300.jpg'); -- item_id = 31
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Mortal Kombat', 'MMA fighter Cole Young seeks out Earth''s greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.', 'Movie', '2021-04-23', 9, 'https://m.media-amazon.com/images/M/MV5BNmRmN2I5M2EtNDA1Ny00N2ZmLWE3YWYtMjQ1NTFjY2Q4NWM5XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 32
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Mortal Kombat', 'MMA fighter Cole Young seeks out Earth''s greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.', 'Movie', '2021-04-23', 14, 'https://m.media-amazon.com/images/M/MV5BNmRmN2I5M2EtNDA1Ny00N2ZmLWE3YWYtMjQ1NTFjY2Q4NWM5XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 33
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Mortal Kombat', 'MMA fighter Cole Young seeks out Earth''s greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.', 'Movie', '2021-04-23', 8, 'https://m.media-amazon.com/images/M/MV5BNmRmN2I5M2EtNDA1Ny00N2ZmLWE3YWYtMjQ1NTFjY2Q4NWM5XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 34
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Pit Bull: A Tale of Lust, Murder and Revenge', 'A lonely ranch-owner is pushed to his limits when two sleazy land developers attempt to trick and abuse him into selling his property.', 'Movie', '2020-01-01', 6, 'https://m.media-amazon.com/images/M/MV5BOTdjOGViMjUtYWE0MS00NDQzLTlmZWQtNjQyMThhMjMwMTI1XkEyXkFqcGdeQXVyNjg5ODE0MDQ@._V1_SX300.jpg'); -- item_id = 35
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Norge i dag', 'A live current affairs program with reports and guests from all over the country.', 'TV Show', '2020-01-01', 15, 'https://m.media-amazon.com/images/M/MV5BMDc1YWE1MjEtODZlMC00MGU1LTk0ZTMtMWZjNDU1ZDJiYjAxXkEyXkFqcGdeQXVyMTA1Mzk1NDMy._V1_SX300.jpg'); -- item_id = 36
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Badalte Rishte', 'Badalte Rishte is a story of changing fortunes. How dramatically and with what consequences the changes are brought about in the human psyche, personality, behaviour and relationships. ...', 'TV Show', '2021-01-01', 6, 'N/A'); -- item_id = 37
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Iowa Press', 'N/A', 'TV Show', '2020-01-01', 15, 'N/A'); -- item_id = 38
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Iowa Press', 'N/A', 'TV Show', '2020-01-01', 16, 'N/A'); -- item_id = 39
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Killer''s Game', 'When a hitman is diagnosed with a terminal illness, he decides to take a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues.', 'Movie', '2024-09-13', 9, 'https://m.media-amazon.com/images/M/MV5BODg4MTBiOGQtN2I5Yi00MWY2LWI1ODktZTUzZjhlYmZjMjFkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 40
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Killer''s Game', 'When a hitman is diagnosed with a terminal illness, he decides to take a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues.', 'Movie', '2024-09-13', 10, 'https://m.media-amazon.com/images/M/MV5BODg4MTBiOGQtN2I5Yi00MWY2LWI1ODktZTUzZjhlYmZjMjFkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 41
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Killer''s Game', 'When a hitman is diagnosed with a terminal illness, he decides to take a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues.', 'Movie', '2024-09-13', 5, 'https://m.media-amazon.com/images/M/MV5BODg4MTBiOGQtN2I5Yi00MWY2LWI1ODktZTUzZjhlYmZjMjFkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 42
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Zamaanat: And Justice for All', 'A unfulfilled love story of a prominent lawyer, ''Shiv Shankar'' who loses his vision in an accident and is thrown into a life of seclusion. He also loses contact with his beloved (Vijayshanti) a doctor by profession. Shiv starts le...', 'Movie', '2025-01-01', 1, 'https://m.media-amazon.com/images/M/MV5BMTgwNzI1NjE2MV5BMl5BanBnXkFtZTcwNzg5OTQxMg@@._V1_SX300.jpg'); -- item_id = 43
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Zamaanat: And Justice for All', 'A unfulfilled love story of a prominent lawyer, ''Shiv Shankar'' who loses his vision in an accident and is thrown into a life of seclusion. He also loses contact with his beloved (Vijayshanti) a doctor by profession. Shiv starts le...', 'Movie', '2025-01-01', 17, 'https://m.media-amazon.com/images/M/MV5BMTgwNzI1NjE2MV5BMl5BanBnXkFtZTcwNzg5OTQxMg@@._V1_SX300.jpg'); -- item_id = 44
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Zamaanat: And Justice for All', 'A unfulfilled love story of a prominent lawyer, ''Shiv Shankar'' who loses his vision in an accident and is thrown into a life of seclusion. He also loses contact with his beloved (Vijayshanti) a doctor by profession. Shiv starts le...', 'Movie', '2025-01-01', 18, 'https://m.media-amazon.com/images/M/MV5BMTgwNzI1NjE2MV5BMl5BanBnXkFtZTcwNzg5OTQxMg@@._V1_SX300.jpg'); -- item_id = 45
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('I giganti del cielo', 'N/A', 'Movie', '2024-01-01', 2, 'N/A'); -- item_id = 46
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Sanatta: The Silence', 'N/A', 'Movie', '2025-01-01', 6, 'N/A'); -- item_id = 47
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Yerkir Nairi', 'The film is dedicated to the 10th anniversary of the Soviet rule in Armenia.', 'Movie', '2023-01-01', 2, 'N/A'); -- item_id = 48
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Perfumed Road', 'Every fragrance a woman wears is composed of two main ingredients. A scent, and ... passion.', 'Movie', '2024-01-01', 2, 'N/A'); -- item_id = 49
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Remedy', 'A NYC artist is witness to his best friend''s murder - or was he? Due to a drug problem, he can''t recall what happened. Now he is the prime suspect and desperately tries to remember before it''s too late.', 'Movie', '2005-03-29', 19, 'https://m.media-amazon.com/images/M/MV5BMTYyNDA5ODEzM15BMl5BanBnXkFtZTcwNDEwOTcyMQ@@._V1_SX300.jpg'); -- item_id = 50
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Remedy', 'A NYC artist is witness to his best friend''s murder - or was he? Due to a drug problem, he can''t recall what happened. Now he is the prime suspect and desperately tries to remember before it''s too late.', 'Movie', '2005-03-29', 1, 'https://m.media-amazon.com/images/M/MV5BMTYyNDA5ODEzM15BMl5BanBnXkFtZTcwNDEwOTcyMQ@@._V1_SX300.jpg'); -- item_id = 51
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Mangalyam', 'N/A', 'TV Show', '2023-09-06', 6, 'N/A'); -- item_id = 52
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Masters of the Universe', 'A young man on Earth discovers a fabulous secret legacy as the prince of an alien planet, and must recover a magic sword and return home to protect his kingdom.', 'Movie', '2026-06-05', 9, 'https://m.media-amazon.com/images/M/MV5BNWE0MDE0NTctNTQ3Zi00ZjJiLTllYzgtZjA2NDg2OGRiZWZlXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 53
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Masters of the Universe', 'A young man on Earth discovers a fabulous secret legacy as the prince of an alien planet, and must recover a magic sword and return home to protect his kingdom.', 'Movie', '2026-06-05', 14, 'https://m.media-amazon.com/images/M/MV5BNWE0MDE0NTctNTQ3Zi00ZjJiLTllYzgtZjA2NDg2OGRiZWZlXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 54
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Masters of the Universe', 'A young man on Earth discovers a fabulous secret legacy as the prince of an alien planet, and must recover a magic sword and return home to protect his kingdom.', 'Movie', '2026-06-05', 17, 'https://m.media-amazon.com/images/M/MV5BNWE0MDE0NTctNTQ3Zi00ZjJiLTllYzgtZjA2NDg2OGRiZWZlXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 55
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Shantaram', 'Lindsay arrives in Mumbai after escaping from an Australian prison. He meets Prabhakar who takes him to his native village where he relaunches his criminal career as Shantaram in the city''s notorious underworld.', 'TV Show', '2022-10-14', 9, 'https://m.media-amazon.com/images/M/MV5BNzdlODA5MWEtOTM3MC00NjZkLTk2MjItMzExZTk1NjUxZGViXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 56
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Shantaram', 'Lindsay arrives in Mumbai after escaping from an Australian prison. He meets Prabhakar who takes him to his native village where he relaunches his criminal career as Shantaram in the city''s notorious underworld.', 'TV Show', '2022-10-14', 14, 'https://m.media-amazon.com/images/M/MV5BNzdlODA5MWEtOTM3MC00NjZkLTk2MjItMzExZTk1NjUxZGViXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 57
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Shantaram', 'Lindsay arrives in Mumbai after escaping from an Australian prison. He meets Prabhakar who takes him to his native village where he relaunches his criminal career as Shantaram in the city''s notorious underworld.', 'TV Show', '2022-10-14', 19, 'https://m.media-amazon.com/images/M/MV5BNzdlODA5MWEtOTM3MC00NjZkLTk2MjItMzExZTk1NjUxZGViXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 58
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('About Face: The Story of the Jewish Refugee Soldiers of World War II', 'Documents the as-yet-untold World War II story of young Jewish men who escaped certain danger at the hands of the Nazis and returned to fight them in Europe and North Africa. Told through the eyes of these men, the film chronicles...', 'Movie', '2020-06-26', 2, 'https://m.media-amazon.com/images/M/MV5BOTkwNzI5ZDctYjVjYi00Y2U1LWI1M2UtYjFhNmQ3MWE0ODgwXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 59
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Flash', 'Barry Allen uses his super speed to change the past, but his attempt to save his family creates a world without super heroes, forcing him to race for his life in order to save the future.', 'Movie', '2023-06-16', 9, 'https://m.media-amazon.com/images/M/MV5BYmE2NzBjNGUtNTJiMy00N2UxLWEyYzMtYzFjODFhMGZlOTgzXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 60
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Flash', 'Barry Allen uses his super speed to change the past, but his attempt to save his family creates a world without super heroes, forcing him to race for his life in order to save the future.', 'Movie', '2023-06-16', 14, 'https://m.media-amazon.com/images/M/MV5BYmE2NzBjNGUtNTJiMy00N2UxLWEyYzMtYzFjODFhMGZlOTgzXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 61
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Flash', 'Barry Allen uses his super speed to change the past, but his attempt to save his family creates a world without super heroes, forcing him to race for his life in order to save the future.', 'Movie', '2023-06-16', 8, 'https://m.media-amazon.com/images/M/MV5BYmE2NzBjNGUtNTJiMy00N2UxLWEyYzMtYzFjODFhMGZlOTgzXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 62
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Surviving in L.A.', 'Kate McCarthy, a former teen sitcom star who trashed her life through drug abuse, is forced to live, fresh out of rehab, on the one remaining piece of property, her business manager, Charlie has kept out of foreclosure - a run-dow...', 'Movie', '2020-08-15', 10, 'https://m.media-amazon.com/images/M/MV5BODg3MDg1Mzg3OF5BMl5BanBnXkFtZTcwODQ0OTExOQ@@._V1_SX300.jpg'); -- item_id = 63
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Surviving in L.A.', 'Kate McCarthy, a former teen sitcom star who trashed her life through drug abuse, is forced to live, fresh out of rehab, on the one remaining piece of property, her business manager, Charlie has kept out of foreclosure - a run-dow...', 'Movie', '2020-08-15', 1, 'https://m.media-amazon.com/images/M/MV5BODg3MDg1Mzg3OF5BMl5BanBnXkFtZTcwODQ0OTExOQ@@._V1_SX300.jpg'); -- item_id = 64
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Surviving in L.A.', 'Kate McCarthy, a former teen sitcom star who trashed her life through drug abuse, is forced to live, fresh out of rehab, on the one remaining piece of property, her business manager, Charlie has kept out of foreclosure - a run-dow...', 'Movie', '2020-08-15', 20, 'https://m.media-amazon.com/images/M/MV5BODg3MDg1Mzg3OF5BMl5BanBnXkFtZTcwODQ0OTExOQ@@._V1_SX300.jpg'); -- item_id = 65
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Nefarious', 'A fast moving, funny and ultimately tragic European road movie about two hedonistic outlaws and their quest to open up a coffeeshop in Amsterdam.', 'Movie', '2024-01-01', 19, 'https://m.media-amazon.com/images/M/MV5BNzVkYWQ1ZGQtNmEyZC00N2VjLTgxNzQtNDI2MDBmZDlhZGRlXkEyXkFqcGdeQXVyNTg0MzE1MjQ@._V1_SX300.jpg'); -- item_id = 66
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Nefarious', 'A fast moving, funny and ultimately tragic European road movie about two hedonistic outlaws and their quest to open up a coffeeshop in Amsterdam.', 'Movie', '2024-01-01', 5, 'https://m.media-amazon.com/images/M/MV5BNzVkYWQ1ZGQtNmEyZC00N2VjLTgxNzQtNDI2MDBmZDlhZGRlXkEyXkFqcGdeQXVyNTg0MzE1MjQ@._V1_SX300.jpg'); -- item_id = 67
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('On Moral Grounds', 'Shot on location in Eastern Europe and in the courtrooms of the United States, this documentary brings to light the saga of WWII restitution and the stories of those who have sought justice...', 'Movie', '2006-04-02', 2, 'N/A'); -- item_id = 68
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Ten Tricks', 'In one night, a madam at a brothel makes plans to get pregnant, while a magician working across the street makes a drastic move to change his life.', 'Movie', '2022-09-27', 10, 'https://m.media-amazon.com/images/M/MV5BMWY0NGUyZDktZWQ2ZS00ZGRiLTlmMTctMzAyOTFiOWE5ZDAxXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 69
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Ten Tricks', 'In one night, a madam at a brothel makes plans to get pregnant, while a magician working across the street makes a drastic move to change his life.', 'Movie', '2022-09-27', 1, 'https://m.media-amazon.com/images/M/MV5BMWY0NGUyZDktZWQ2ZS00ZGRiLTlmMTctMzAyOTFiOWE5ZDAxXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 70
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Anywhere Anytime', 'A marriage is about to become bait to the tabloid gossip of Bollywood''s hot on-screen pair, Shekahar (Aashish Chowdhary) and Jaya (Sheetal Malhar). Thus further agitating the already ...', 'Movie', '2025-01-01', 1, 'N/A'); -- item_id = 71
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Anywhere Anytime', 'A marriage is about to become bait to the tabloid gossip of Bollywood''s hot on-screen pair, Shekahar (Aashish Chowdhary) and Jaya (Sheetal Malhar). Thus further agitating the already ...', 'Movie', '2025-01-01', 20, 'N/A'); -- item_id = 72
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Anywhere Anytime', 'A marriage is about to become bait to the tabloid gossip of Bollywood''s hot on-screen pair, Shekahar (Aashish Chowdhary) and Jaya (Sheetal Malhar). Thus further agitating the already ...', 'Movie', '2025-01-01', 5, 'N/A'); -- item_id = 73
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Soccer Academy', '"The Soccer Academy" is a recurring television series presently distributed throughout North Africa, The Middle East and the Near East. It is a soccer, travel, adventure and culture show ...', 'TV Show', '2022-01-01', 14, 'N/A'); -- item_id = 74
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Soccer Academy', '"The Soccer Academy" is a recurring television series presently distributed throughout North Africa, The Middle East and the Near East. It is a soccer, travel, adventure and culture show ...', 'TV Show', '2022-01-01', 17, 'N/A'); -- item_id = 75
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Soccer Academy', '"The Soccer Academy" is a recurring television series presently distributed throughout North Africa, The Middle East and the Near East. It is a soccer, travel, adventure and culture show ...', 'TV Show', '2022-01-01', 16, 'N/A'); -- item_id = 76
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Twits', 'A pair of wicked pranksters plan an elaborate heist along with their crew of highly-trained animals.', 'Movie', '2025-06-13', 21, 'https://m.media-amazon.com/images/M/MV5BNDAyNWJlZDEtZWYyOS00ZmVjLWI0MTAtMDc5MGZjNWRkOTViXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg'); -- item_id = 77
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Twits', 'A pair of wicked pranksters plan an elaborate heist along with their crew of highly-trained animals.', 'Movie', '2025-06-13', 14, 'https://m.media-amazon.com/images/M/MV5BNDAyNWJlZDEtZWYyOS00ZmVjLWI0MTAtMDc5MGZjNWRkOTViXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg'); -- item_id = 78
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Twits', 'A pair of wicked pranksters plan an elaborate heist along with their crew of highly-trained animals.', 'Movie', '2025-06-13', 10, 'https://m.media-amazon.com/images/M/MV5BNDAyNWJlZDEtZWYyOS00ZmVjLWI0MTAtMDc5MGZjNWRkOTViXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg'); -- item_id = 79
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Without Remorse', 'An elite Navy SEAL goes on a path to avenge his wife''s murder only to find himself inside of a larger conspiracy.', 'Movie', '2021-04-30', 9, 'https://m.media-amazon.com/images/M/MV5BNzE0NjU1MmUtZWUzMS00ZWRiLWE5ZjYtODk3NmRlMmExYWI1XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 80
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Without Remorse', 'An elite Navy SEAL goes on a path to avenge his wife''s murder only to find himself inside of a larger conspiracy.', 'Movie', '2021-04-30', 1, 'https://m.media-amazon.com/images/M/MV5BNzE0NjU1MmUtZWUzMS00ZWRiLWE5ZjYtODk3NmRlMmExYWI1XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 81
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Without Remorse', 'An elite Navy SEAL goes on a path to avenge his wife''s murder only to find himself inside of a larger conspiracy.', 'Movie', '2021-04-30', 5, 'https://m.media-amazon.com/images/M/MV5BNzE0NjU1MmUtZWUzMS00ZWRiLWE5ZjYtODk3NmRlMmExYWI1XkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 82
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Moe', 'A fun-loving Latino theater director lives his remaining days to the fullest as he suffers from AIDS.', 'Movie', '2008-12-01', 10, 'N/A'); -- item_id = 83
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Moe', 'A fun-loving Latino theater director lives his remaining days to the fullest as he suffers from AIDS.', 'Movie', '2008-12-01', 1, 'N/A'); -- item_id = 84
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Moe', 'A fun-loving Latino theater director lives his remaining days to the fullest as he suffers from AIDS.', 'Movie', '2008-12-01', 22, 'N/A'); -- item_id = 85
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('American Surfrider', 'Society needs a reboot after the devastating activities of 2020. Some of post-pandemic society will need ways to improve their mental health and this project serves as a soulful reminder of how some people found their happiness or...', 'Movie', '2008-05-20', 2, 'N/A'); -- item_id = 86
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Vendetta', 'Madera Verde is cerebrating its bicentennial when a killer wreaks havoc on the town. Now two sisters with a tragic past are next.', 'Movie', '2022-04-01', 3, 'https://m.media-amazon.com/images/M/MV5BNDg4OTVkZTMtZWU1OS00YTQxLTg2ZjUtNzVkYjg5NDczNzVmXkEyXkFqcGdeQXVyMjAxNDQ1ODc@._V1_SX300.jpg'); -- item_id = 87
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Vendetta', 'Madera Verde is cerebrating its bicentennial when a killer wreaks havoc on the town. Now two sisters with a tragic past are next.', 'Movie', '2022-04-01', 18, 'https://m.media-amazon.com/images/M/MV5BNDg4OTVkZTMtZWU1OS00YTQxLTg2ZjUtNzVkYjg5NDczNzVmXkEyXkFqcGdeQXVyMjAxNDQ1ODc@._V1_SX300.jpg'); -- item_id = 88
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Vendetta', 'Madera Verde is cerebrating its bicentennial when a killer wreaks havoc on the town. Now two sisters with a tragic past are next.', 'Movie', '2022-04-01', 5, 'https://m.media-amazon.com/images/M/MV5BNDg4OTVkZTMtZWU1OS00YTQxLTg2ZjUtNzVkYjg5NDczNzVmXkEyXkFqcGdeQXVyMjAxNDQ1ODc@._V1_SX300.jpg'); -- item_id = 89
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Un homme à femmes', 'N/A', 'Movie', '2024-01-01', 10, 'N/A'); -- item_id = 90
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Foundation', 'A complex saga of humans scattered on planets throughout the galaxy all living under the rule of the Galactic Empire.', 'TV Show', '2021-09-24', 1, 'https://m.media-amazon.com/images/M/MV5BOTRiNGMxOGMtMTQ5Ni00OGVjLWE3YWEtZDNhYzlmMjc2ZWUwXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 91
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Foundation', 'A complex saga of humans scattered on planets throughout the galaxy all living under the rule of the Galactic Empire.', 'TV Show', '2021-09-24', 11, 'https://m.media-amazon.com/images/M/MV5BOTRiNGMxOGMtMTQ5Ni00OGVjLWE3YWEtZDNhYzlmMjc2ZWUwXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 92
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Witches', 'A young boy and his grandmother have a run-in with a coven of witches and their leader.', 'Movie', '2020-10-22', 14, 'https://m.media-amazon.com/images/M/MV5BZjRiYWFmZTYtYTBmZi00ZmM0LWFjODgtNWZmNjQyYjQ5OTRkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 93
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Witches', 'A young boy and his grandmother have a run-in with a coven of witches and their leader.', 'Movie', '2020-10-22', 10, 'https://m.media-amazon.com/images/M/MV5BZjRiYWFmZTYtYTBmZi00ZmM0LWFjODgtNWZmNjQyYjQ5OTRkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 94
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Witches', 'A young boy and his grandmother have a run-in with a coven of witches and their leader.', 'Movie', '2020-10-22', 17, 'https://m.media-amazon.com/images/M/MV5BZjRiYWFmZTYtYTBmZi00ZmM0LWFjODgtNWZmNjQyYjQ5OTRkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 95
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Swarm', 'Ecological thriller about the delicate interconnectedness between mankind and Earth.', 'TV Show', '2023-09-12', 1, 'https://m.media-amazon.com/images/M/MV5BMGQzZjZlNjctMTZhMy00Njg3LWIyNzAtODEyZTFhNGRkMjUwXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 96
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Swarm', 'Ecological thriller about the delicate interconnectedness between mankind and Earth.', 'TV Show', '2023-09-12', 18, 'https://m.media-amazon.com/images/M/MV5BMGQzZjZlNjctMTZhMy00Njg3LWIyNzAtODEyZTFhNGRkMjUwXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 97
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('The Swarm', 'Ecological thriller about the delicate interconnectedness between mankind and Earth.', 'TV Show', '2023-09-12', 11, 'https://m.media-amazon.com/images/M/MV5BMGQzZjZlNjctMTZhMy00Njg3LWIyNzAtODEyZTFhNGRkMjUwXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 98
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Jungle Cruise', 'Based on Disneyland''s theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.', 'Movie', '2021-07-30', 9, 'https://m.media-amazon.com/images/M/MV5BMWU5ZTBkMjQtMzg2Yi00ZmJlLTk4YWEtYTc0ZjU1YzE1NGNkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 99
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Jungle Cruise', 'Based on Disneyland''s theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.', 'Movie', '2021-07-30', 14, 'https://m.media-amazon.com/images/M/MV5BMWU5ZTBkMjQtMzg2Yi00ZmJlLTk4YWEtYTc0ZjU1YzE1NGNkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 100
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Jungle Cruise', 'Based on Disneyland''s theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.', 'Movie', '2021-07-30', 10, 'https://m.media-amazon.com/images/M/MV5BMWU5ZTBkMjQtMzg2Yi00ZmJlLTk4YWEtYTc0ZjU1YzE1NGNkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 101
INSERT INTO ContentItem (title, description, content_type, release_date, genre_id, image_url) VALUES ('Jungle Cruise', 'Based on Disneyland''s theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.', 'Book', '2021-07-30', 10, 'https://m.media-amazon.com/images/M/MV5BMWU5ZTBkMjQtMzg2Yi00ZmJlLTk4YWEtYTc0ZjU1YzE1NGNkXkEyXkFqcGc@._V1_SX300.jpg'); -- item_id = 101
